

# Set up

Import packages
```{r}
suppressPackageStartupMessages({
  suppressWarnings({
    library(tidyverse)
    library(readxl)
    library(here)
  })})
```

Set settings and universal variables
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here())
```

# Import and process data

Demand unit key--provided by Kristin via email on 26/2/2026.
Wrangle so we have two columns. One row per PWSID, with 2nd column indicating demand unit it pertains to. 
```{r}
du_key = read_excel("Data/Source/Demand unit key/Systems_served_by_DU_pwsid.xlsx")%>%
  rename(id = 1)%>%
  mutate(id = str_trim(str_replace_all(id, "[\r\n]+", " ")),
           is_du = ifelse(startsWith(id, "CA") | grepl("San Gorgonio|Upper San Gabriel|Orange County", id), 0, 1),
         demand_unit = if_else(is_du == 1, id, NA))%>%
  fill(demand_unit, .direction = "down")%>%
  filter(is_du != 1)%>%
  rename(pwsid = 1)%>%
  select(-is_du)

du_key%>%
  select(demand_unit)%>%
  unique()%>%
  filter(!demand_unit %in% joined$demand_unit)

du_key%>%
  filter(demand_unit == "02_NU")

network_data%>%
  filter(pwsid %in% c("CA4500093", "CA4510001", "CA4510007", "CA5200512", "CA5200645", "CA5210005"))
```


```{r}
network_data = read.csv("Data/Outputs/20251215_network_joined.csv")%>%
  select(pwsid, system_lat, system_lon, pop_served)
```

```{r}
joined = du_key%>%
  inner_join(., network_data, by = "pwsid")%>%
  unique()%>%
  group_by(demand_unit)%>%
  filter(pop_served == max(pop_served, na.rm = T))%>%
  rename(lat = system_lat, lon = system_lon, pwsid_coords_from = pwsid)%>%
  select(demand_unit, lat, lon, pwsid_coords_from)

joined

left_join(du_key, network_data, by = "pwsid")%>%
  filter(is.na(system_lat))%>%
  select(demand_unit)%>%
  unique()

write.csv(joined, "Data/Outputs/20260226_demand_unit_lat_longs.csv")
```


