
# Set up

Import packages
```{r}
suppressPackageStartupMessages({
  suppressWarnings({
  library(tidyverse)   # Data wrangling
  library(here)        # File management
  library(readxl)      # Read excel files
  })})
```

Set settings and universal variables
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here())
```

# Import data

Cleaned & deduplicated network data
```{r}
network = read.csv("Data/Outputs/20251002_network_data_cleaned.csv")
```

# Create source ID column
Use PWSID as source ID if source type is a PWS, otherwise generating a numerical source ID for each source (grouping by source name since there can be multiple rows with the same source)
```{r}
source_ids = network%>%
  group_by(Source) %>%
  mutate(group_id = paste("source", cur_group_id(), sep = "_")) %>%
  ungroup() %>%
  mutate(source_id = ifelse(Source_type == "PWS", Source, group_id)) %>%
  select(Source, source_id)%>%
  unique()
```

Check to make sure it worked properly
```{r}
n_distinct(network$Source)
n_distinct(source_ids$source_id)

network%>%
  left_join(., source_ids, by = "Source")%>%
  group_by(Source)%>%
  filter(n_distinct(source_id) > 1)%>%
  arrange(Source)
```
# Export
```{r}
write.csv(source_ids, "Data/Outputs/20251002_source_id_key.csv", row.names = F)
```





